language: php

sudo: false

env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

php:
  - 5.6
#  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

  exclude:
    - php: hhvm
      env: PHP_BIN=php-cgi

#  include:
#    - php: 5.6
#      env: dependencies="--prefer-lowest --prefer-stable" PHP_BIN=php

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
#  - pecl install mysqli
  - pecl install pdo_mysql

install:
  - composer update --no-interaction --prefer-dist $dependencies

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
#  - phpenv config-add tests/php-unix.ini
  - composer create-project --prefer-source --no-interaction jakub-onderka/php-parallel-lint vendor/php-parallel-lint
  - php vendor/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - composer create-project --prefer-source --no-interaction nette/code-checker vendor/code-checker
  - php vendor/code-checker/src/code-checker.php -d src
  - php vendor/code-checker/src/code-checker.php -d tests

script:
  - vendor/bin/tester -p $PHP_BIN -s tests

after_failure:
  # Print the *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
